//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ___VARIABLE_productName:identifier___WireframeProtocol: class {

}
//MARK: Presenter -
protocol ___VARIABLE_productName:identifier___PresenterProtocol: class {

}

//MARK: Interactor -
protocol ___VARIABLE_productName:identifier___InteractorProtocol: class {

  var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?  { get set }
}

//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: class {

  var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?  { get set }
}
