//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//  Template improved by Hitendra Hckr https://github.com/hitendradeveloper
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___PresenterProtocol, ___FILEBASENAMEASIDENTIFIER___InteractorOutputProtocol {

    weak var view: ___FILEBASENAMEASIDENTIFIER___ViewProtocol?
    var interactor: ___FILEBASENAMEASIDENTIFIER___InteractorInputProtocol!
    var router: ___FILEBASENAMEASIDENTIFIER___WireframeProtocol!
}
