//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___PresenterType
{
    // MARK: - Router
    
    let router: ___VARIABLE_productName:identifier___Type
    
    // MARK: - Initializer
    
    required init(
        router: ___VARIABLE_productName:identifier___Type)
    {
        self.router = router
    }
}
