//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

protocol ___VARIABLE_productName:identifier___PresenterType: PresenterType
{
    var router: ___VARIABLE_productName:identifier___RouterType { get }
    
    init(
        router: ___VARIABLE_productName:identifier___RouterType)
}
