//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

protocol ___VARIABLE_productName:identifier___ViewType: ViewType
{
    var presenter: ___VARIABLE_productName:identifier___PresenterType { get }
    
    init(
        presenter: ___VARIABLE_productName:identifier___PresenterType)
}
